// svelte-todo/src/Task.svelte
<script lang="ts">
import type { Task } from "svelte/internal";

    import {taskList} from "./stores"
    import type {TaskType} from "./types"

    export let task:TaskType
    const handleOnClick = () => {
        const newTask:TaskType[] = $taskList.map((t,i) => {
            if (task.id !== i) return t
            return {
                id: t.id,
                text: t.text,
                done:!t.done
            }
        })
        taskList.update(() => [...newTask])
    }
</script>

<li>
    <input type="checkbox" checked={task.done} on:click={handleOnClick}>
    <p>{task.text}</p>
</li>

<style>
    li {
        display:flex;
        margin:10px;
    }

    p {
        margin:0;
        margin-left: 10px;
    }
</style>

// react-todo/src/Task.tsx
import React, { Dispatch, useRef } from 'react';
import { TaskType } from './types';

type Props = TaskType & {
    setTasks:Dispatch<TaskType[]>,
    tasks:TaskType[]
}

const Task:React.FC<Props> = (props: Props) => {
    const ref = useRef(null);
    const handleOnClick = () => {
        const newTasks = props.tasks.map((task,i) => {
            if (props.id !== i) return task
            return {
                id: task.id,
                text: task.text,
                done:!task.done
            }
        }) 
        props.setTasks(newTasks);
    }
    return ( 
        <li ref={ref} style={{display: "flex", margin:10}}>
            <input type="checkbox" checked={props.done} onClick={handleOnClick}/>
            <p style={{margin: 0}}>{props.text}</p>
        </li>
    )
}

export default Task;
